---
# tasks file for hswong3i.webmin

- name: apt-key add
  apt_key:
    url="{{ item }}"
    state=present
  with_items:
    - http://www.webmin.com/jcameron-key.asc
  notify: restart webmin
  tags: hswong3i.webmin

- name: apt-add-repository
  apt_repository:
    repo="{{ item }}"
    state=present
  with_items:
    - deb http://download.webmin.com/download/repository sarge contrib
    - deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib
  notify: restart webmin
  tags: hswong3i.webmin

- name: apt-get install
  apt:
    name="{{ item }}"
    state=latest
  with_items:
    - ufw
    - webmin
  notify: restart webmin
  tags: hswong3i.webmin

- name: replace in file
  replace:
    dest={{ item.dest }}
    regexp={{ item.regexp }}
    replace={{ item.replace }}
  with_items:
    - { dest: '/etc/webmin/miniserv.conf', regexp: '^listen=.*$', replace: "listen={{ webmin_listen }}" }
    - { dest: '/etc/webmin/miniserv.conf', regexp: '^port=.*$', replace: "port={{ webmin_port }}" }
    - { dest: '/etc/webmin/miniserv.conf', regexp: '^ssl=.*$', replace: "ssl={{ webmin_ssl }}" }
  notify: restart webmin
  tags: hswong3i.webmin

- name: enable incomming connection
  ufw:
    to_port={{ item }}
    proto=tcp
    rule=allow
  with_items:
    - "{{ webmin_port }}"
  notify: restart webmin
  tags: hswong3i.webmin
